FROM ubuntu:18.04

# Buat PHP 7.4
RUN apt install php7.4
RUN apt-get install php7.4-cli php7.4-fpm php7.4-bcmath php7.4-curl php7.4-gd php7.4-intl php7.4-json php7.4-mbstring php7.4-mysql php7.4-opcache php7.4-sqlite3 php7.4-xml php7.4-zip


# Forward Port
EXPOSE 80 6000
